spring:
  application:
    name: devblog

  datasource:
    url: jdbc:mysql://localhost:3306/devblog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: devblog
    password: devblog1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug


app:
  jwt:
    secret: "ee19e6660a0ac7d9378d8355673b04a8165a9b66d22f48af8708f0258fa1d6593fb7abbd65941749c99d58ee14b6468d815b285e28fee2fa2924883f5fa553fb"
    expiration-seconds: 3600
