spring:
  application:
    name: devblog

  datasource:
    url: jdbc:mysql://localhost:3306/devblog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: devblog
    password: devblog1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug